module.exports = [
    {cateName: '奇幻修真', cateID: 'sort3', startPage: 1},
    {cateName: '奇幻魔法', cateID: 'sort13', startPage: 1},
    {cateName: '异术超能', cateID: 'sort1', startPage: 1},
    {cateName: '东方传奇', cateID: 'sort12', startPage: 1},
    {cateName: '王朝争霸', cateID: 'sort14', startPage: 1},
    {cateName: '江湖武侠', cateID: 'sort15', startPage: 1},
    {cateName: '未来幻想', cateID: 'sort9', startPage: 1},
    {cateName: '灵异鬼怪', cateID: 'sort10', startPage: 1},
    {cateName: '探险揭秘', cateID: 'sort22', startPage: 1},
    {cateName: '历史传记', cateID: 'sort6', startPage: 1},
    {cateName: '特种军旅', cateID: 'sort7', startPage: 1},
    {cateName: '虚拟网游', cateID: 'sort16', startPage: 1},
    {cateName: '竞技体育', cateID: 'sort8', startPage: 1},
    {cateName: '魔幻女强', cateID: 'sort2', startPage: 1},
    {cateName: '都市婚姻', cateID: 'sort4', startPage: 1},
    {cateName: '百合之恋', cateID: 'sort5', startPage: 1},
    {cateName: '同人美文', cateID: 'sort11', startPage: 1},
    {cateName: '穿越架空', cateID: 'sort17', startPage: 1},
    {cateName: '王室贵族', cateID: 'sort18', startPage: 1},
    {cateName: '魔法校园', cateID: 'sort19', startPage: 1},
    {cateName: '乡土布衣', cateID: 'sort20', startPage: 1},
    {cateName: '官职商战', cateID: 'sort21', startPage: 1},
    {cateName: '间谍暗战', cateID: 'sort23', startPage: 1},
    {cateName: '唯美言情', cateID: 'sort24', startPage: 1},
    {cateName: '诗歌文集', cateID: 'sort25', startPage: 1}
]
