module.exports = [
    {cateName: '奇幻修真', cateID: 'sort3'},
    {cateName: '奇幻魔法', cateID: 'sort13'},
    {cateName: '异术超能', cateID: 'sort1'},
    {cateName: '东方传奇', cateID: 'sort12'},
    {cateName: '王朝争霸', cateID: 'sort14'},
    {cateName: '江湖武侠', cateID: 'sort15'},
    {cateName: '未来幻想', cateID: 'sort9'},
    {cateName: '灵异鬼怪', cateID: 'sort10'},
    {cateName: '探险揭秘', cateID: 'sort22'},
    {cateName: '历史传记', cateID: 'sort6'},
    {cateName: '特种军旅', cateID: 'sort7'},
    {cateName: '虚拟网游', cateID: 'sort16'},
    {cateName: '竞技体育', cateID: 'sort8'},
    {cateName: '魔幻女强', cateID: 'sort2'},
    {cateName: '都市婚姻', cateID: 'sort4'},
    {cateName: '百合之恋', cateID: 'sort5'},
    {cateName: '同人美文', cateID: 'sort11'},
    {cateName: '穿越架空', cateID: 'sort17'},
    {cateName: '王室贵族', cateID: 'sort18'},
    {cateName: '魔法校园', cateID: 'sort19'},
    {cateName: '乡土布衣', cateID: 'sort20'},
    {cateName: '官职商战', cateID: 'sort21'},
    {cateName: '间谍暗战', cateID: 'sort23'},
    {cateName: '唯美言情', cateID: 'sort24'},
    {cateName: '诗歌文集', cateID: 'sort25'}
    ]
